### ISSUE TITLE
audio demo not working

### ISSUE THREAD

**Issue by hdumcke** [mangdangroboticsclub/mini_pupper_2_bsp#48]
### Reproduction steps

run demos/audio_test.py

### Actual results

ubuntu@minipupperv2:~/mini_pupper_bsp/demos$ chmod +x audio_test.py
ubuntu@minipupperv2:~/mini_pupper_bsp/demos$ ./audio_test.py
Simple mixer control 'Headphone',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback 400 [100%] [4.00dB] [on]
Mini Pupper 2 audio record start...
Traceback (most recent call last):
  File "/home/ubuntu/mini_pupper_bsp/demos/./audio_test.py", line 35, in <module>
    record = sd.rec(int(duration * fs), samplerate=fs, channels=2)
  File "/usr/local/lib/python3.10/dist-packages/sounddevice.py", line 276, in rec
    ctx.start_stream(InputStream, samplerate, ctx.input_channels,
  File "/usr/local/lib/python3.10/dist-packages/sounddevice.py", line 2582, in start_stream
    self.stream = StreamClass(samplerate=samplerate,
  File "/usr/local/lib/python3.10/dist-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/usr/local/lib/python3.10/dist-packages/sounddevice.py", line 817, in __init__
    _get_stream_parameters(kind, device, channels, dtype, latency,
  File "/usr/local/lib/python3.10/dist-packages/sounddevice.py", line 2660, in _get_stream_parameters
    info = query_devices(device)
  File "/usr/local/lib/python3.10/dist-packages/sounddevice.py", line 569, in query_devices
    raise PortAudioError(f'Error querying device {device}')
sounddevice.PortAudioError: Error querying device -1

### Expected results

no Python trace

### Version

Mini Pupper 2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mangdangroboticsclub** [comment]
already fixed.
